#include "Eagle.h"
#include "./unit_tests/test_calc.c"

int main()
{
    EAGLE_INIT();

    ADD_TEST(SIMPLE_MATH, T_ADD);
    ADD_TEST(SIMPLE_MATH, T_MULT);
    ADD_TEST(SIMPLE_MATH, T_FAIL);
    ADD_TEST(SIMPLE_MATH, T_ADD);

    ADD_TEST(ANOTHER_COL, T_ADD);
    ADD_TEST(ANOTHER_COL, T_ADD);
    ADD_TEST(ANOTHER_COL, T_ADD);
    ADD_TEST(ANOTHER_COL, T_ADD);
    ADD_TEST(ANOTHER_COL, T_ADD);

    ADD_TEST(THIRD_COLL, T_FAIL);
    ADD_TEST(THIRD_COLL, T_ADD);
    ADD_TEST(THIRD_COLL, T_ADD);
    ADD_TEST(THIRD_COLL, T_FAIL);

    RUN_ALL();

    EAGLE_END();
}